### ISSUE TITLE
Object of type VideoLocalization is not JSON serializable

### ISSUE THREAD

**Issue by betterthanever2** [dunkyl/SlyPyYTDAPI#17]
Trace probably won't be very useful, but here it is anyway:

```
Traceback (most recent call last):
  File "D:\up\code\wapatools\bases\wapaganda\media\update_service.py", line 32, in run_update
    await self.update_youtube()
  File "D:\up\code\wapatools\bases\wapaganda\media\update_service.py", line 49, in update_youtube
    await platform.update_targets(platform_targets)
  File "D:\up\code\wapatools\bases\wapaganda\media\platforms\youtube.py", line 260, in update_targets
    await self.update_target(target)
  File "D:\up\code\wapatools\bases\wapaganda\media\platforms\youtube.py", line 227, in update_target
    await target.fetch_target_updates()
  File "D:\up\code\wapatools\bases\wapaganda\media\platforms\youtube.py", line 75, in fetch_target_updates
    await self.session.commit()
  File "D:\up\code\wapatools\.venv\Lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 1009, in commit
    await greenlet_spawn(self.sync_session.commit)
  File "D:\up\code\wapatools\.venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 203, in greenlet_spawn
    result = context.switch(value)
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\up\code\wapatools\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "D:\up\code\wapatools\.venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "D:\up\code\wapatools\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "D:\up\code\wapatools\.venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "D:\up\code\wapatools\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "D:\up\code\wapatools\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4352, in flush
    self._flush(objects)
  File "D:\up\code\wapatools\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4487, in _flush
    with util.safe_reraise():
  File "D:\up\code\wapatools\.venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "D:\up\code\wapatools\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4448, in _flush
    flush_context.execute()
  File "D:\up\code\wapatools\.venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "D:\up\code\wapatools\.venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "D:\up\code\wapatools\.venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "D:\up\code\wapatools\.venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1143, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "D:\up\code\wapatools\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "D:\up\code\wapatools\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\up\code\wapatools\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\up\code\wapatools\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1844, in _execute_context
    return self._exec_insertmany_context(dialect, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\up\code\wapatools\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2126, in _exec_insertmany_context
    self._handle_dbapi_exception(
  File "D:\up\code\wapatools\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2358, in _handle_dbapi_exception
    raise exc_info[1].with_traceback(exc_info[2])
  File "D:\up\code\wapatools\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2118, in _exec_insertmany_context
    dialect.do_execute(
  File "D:\up\code\wapatools\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "D:\up\code\wapatools\.venv\Lib\site-packages\sqlalchemy\dialects\postgresql\psycopg.py", line 587, in execute
    result = self.await_(self._cursor.execute(query, params, **kw))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\up\code\wapatools\.venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\up\code\wapatools\.venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "D:\up\code\wapatools\.venv\Lib\site-packages\psycopg\cursor_async.py", line 93, in execute
    await self._conn.wait(
  File "D:\up\code\wapatools\.venv\Lib\site-packages\psycopg\connection_async.py", line 414, in wait
    return await waiting.wait_async(gen, self.pgconn.socket, interval=interval)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\up\code\wapatools\.venv\Lib\site-packages\psycopg\waiting.py", line 132, in wait_async
    s = next(gen)
        ^^^^^^^^^
  File "D:\up\code\wapatools\.venv\Lib\site-packages\psycopg\_cursor_base.py", line 195, in _execute_gen
    pgq = self._convert_query(query, params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\up\code\wapatools\.venv\Lib\site-packages\psycopg\_cursor_base.py", line 455, in _convert_query
    pgq.convert(query, params)
  File "D:\up\code\wapatools\.venv\Lib\site-packages\psycopg\_queries.py", line 96, in convert
    self.dump(vars)
  File "D:\up\code\wapatools\.venv\Lib\site-packages\psycopg\_queries.py", line 107, in dump
    self.params = self._tx.dump_sequence(params, self._want_formats)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "psycopg_binary\\_psycopg/transform.pyx", line 352, in psycopg_binary._psycopg.Transformer.dump_sequence
  File "psycopg_binary\\_psycopg/transform.pyx", line 403, in psycopg_binary._psycopg.Transformer.dump_sequence
  File "D:\up\code\wapatools\.venv\Lib\site-packages\psycopg\types\json.py", line 153, in dump
    data = dumps(obj)
           ^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type VideoLocalization is not JSON serializable
```

This occurs when I apply `to_dict` method on _some_ items. I'm quite confused about how it works, tbh. But to provide you with more context: the update relates to channel with id `UCW1Rq2slBb0rNuu2ZRJwZNw`. I get several videos from it: 

- `5BbDcnOYQUM`. Localization appear as a normal JSON object

```
'localizations': {
'ru': {
'title': 'My evening',
'description': '''★VK★     https://new.vk.com/zhenya_lebedev_2016★Instagram★    https://www.instagram.com/zhenya_lebe...''',},}
```

- `2C_wIf1EQr8` Localization is None.

The next item fails with the exception above. I'm guessing, the trace has no mention of Sly because producing an object instead of a dictionary is not an error, but then my attempt to serialize it fails.

**Comment by dunkyl** [comment]
I was not able to recreate your issue exactly, but I was able to get a similar error from datetime. I switched the implementation of `to_dict()` to use my library designed to do exactly this kind of type conversion for serialization. I didn't do that earlier since I still needed to add a feature to opt into ignoring certain attributes though.

I published that version, but based on these two videos I am not quite sure if it is a complete solution yet.

**Comment by betterthanever2** [comment]
It's not: I'm still getting the same serialization error on `Localizations` and `LiveStreamingDetails` fields

**Comment by dunkyl** [comment]
Are you certain that you are using the result of to_dict, and not Sqlachlemy's serializer?

**Comment by betterthanever2** [comment]
> Are you certain that you are using the result of to_dict, and not Sqlachlemy's serializer?

As a matter of fact, it may not be about `to_dict` method. I have disabled the line that does it, and the exceptions still occurred. I disabled code for localization and livestreamdetails altogether, and then it started working. Here's my function for parsing a video:

```
async def parse_raw_item(self, ytb_obj) -> YoutubeVid:
        # logfire.debug(f"Processing item {ytb_obj.to_dict()}")

        ## NOTE: objects for livestream_details and localizations are not used because they fail to serialize
        ## TODO: when the slyapi is updated with good fix, create a job to update old records.
        # livestream = ytb_obj.livestream_details
        # if livestream:
        #     for attr in dir(livestream):
        #         if type(attr) is datetime:
        #             setattr(livestream, attr, arrow.get(attr).format())
        #     livestream_details = livestream
        # else:
        #     livestream_details = None

        # localizations = ytb_obj.localizations
        # if localizations:
        #     localizations_data = localizations
        # else:
        #     localizations_data = None

        content_details = ytb_obj.content_details
        if content_details:
            is_licensed = content_details.is_licensed
            blocked_in = content_details.blocked_in
            allowed_in = content_details.allowed_in
        else:
            is_licensed = blocked_in = allowed_in = None

        item = YoutubeVid(
            stats_updated_on=arrow.now().datetime,
            segment_id=None,
            youtube_channel_id=self.channel.id,
            youtube_id=ytb_obj.id,
            aired_on=arrow.get(ytb_obj.published_at).datetime,
            title=ytb_obj.title,
            duration=ytb_obj.duration or 0,
            description=ytb_obj.description,
            views_count=ytb_obj.view_count or 0,
            likes_count=ytb_obj.like_count or 0,
            comments_count=ytb_obj.comment_count or 0,
            privacy_status=ytb_obj.privacy,
            is_livestream=ytb_obj.is_livestream,
            auto_default_lang=ytb_obj.default_audio_language,
            is_licensed=is_licensed,
            topic_categories=ytb_obj.topic_categories,
            # livestream_details=livestream_details,
            blocked_in=blocked_in,
            allowed_in=allowed_in,
            # localizations=localizations_data,
            recording_date=ytb_obj.recorded_at,
            cluster_id=None,
            relevance_status_id=2,
        )
        return item
```

I have no idea what fails, sorry.

**Comment by dunkyl** [comment]
If "YoutubeVid" is stored in directly SQL-like data model, then this makes sense. Columns having a type that mentions a non-scalar type usually requires some special adaption. In my opinion, this is a challenge much closer to your use case and is out of scope for this library to solve by itself.

However, for this specific function, here is what I might do:

```py
async def parse_raw_item(self, ytb_obj) -> YoutubeVid:
        ytb_json = ytb_obj.to_dict()
        # logfire.debug(f"Processing item {ytb_json}")

        livestream_details = ytb_json['livestream_details']
        localizations = ytb_json['localizations']

        # rest is the same besides uncommenting the two args for creating item
        content_details = ytb_obj.content_details
        if content_details:
            is_licensed = content_details.is_licensed
            blocked_in = content_details.blocked_in
            allowed_in = content_details.allowed_in
        else:
            is_licensed = blocked_in = allowed_in = None

        item = YoutubeVid(
            stats_updated_on=arrow.now().datetime,
            segment_id=None,
            youtube_channel_id=self.channel.id,
            youtube_id=ytb_obj.id,
            aired_on=arrow.get(ytb_obj.published_at).datetime,
            title=ytb_obj.title,
            duration=ytb_obj.duration or 0,
            description=ytb_obj.description,
            views_count=ytb_obj.view_count or 0,
            likes_count=ytb_obj.like_count or 0,
            comments_count=ytb_obj.comment_count or 0,
            privacy_status=ytb_obj.privacy,
            is_livestream=ytb_obj.is_livestream,
            auto_default_lang=ytb_obj.default_audio_language,
            is_licensed=is_licensed,
            topic_categories=ytb_obj.topic_categories,
            livestream_details=livestream_details,
            blocked_in=blocked_in,
            allowed_in=allowed_in,
            localizations=localizations,
            recording_date=ytb_obj.recorded_at,
            cluster_id=None,
            relevance_status_id=2,
        )
        return item
```

Also, cool, I did not know about the Arrow library, it looks useful!

**Comment by betterthanever2** [comment]
Thanks. Now I have to retire to a monastery, and contemplate why this hasn't occurred to me.
